branches:
  only:
  - master

sudo: required

services:
  - docker

language: go

os: linux

dist: trusty

before_install:
  - docker pull yukinying/latex

install:
  - go get -u github.com/protograph/protographer/cmd/protographer

script:
  - protographer -in yaml -out tex
  - set -e; for file in tex/*.tex; do docker run -v $(pwd)/tex:/tex --workdir /tex --rm --name latex yukinying/latex pdflatex --halt-on-error "/$file"; done

after_success:
  - echo "SUCCESS!"
