language: go
os: linux
dist: trusty
sudo: required
group: edge

branches:
  only:
  - master

services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_18e972c08e0f_key -iv $encrypted_18e972c08e0f_iv
  -in deploy.key.enc -out deploy.key -d
- chmod 600 deploy.key

install:
- make prepare

script:
- make all

after_success:
- echo "SUCCESS!"
- make commit
