language: go
os: linux
dist: trusty
sudo: required

branches:
  only:
  - master

services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_18e972c08e0f_key -iv $encrypted_18e972c08e0f_iv
  -in deploy.key.enc -out deploy.key -d
- chmod 600 deploy.key

install:
- go get -u github.com/protograph/protographer/cmd/protographer
- docker pull yukinying/latex

script:
- protographer -in yaml -out tex
- set -e; for file in tex/*.tex; do docker run -v $(pwd)/tex:/tex --workdir /tex --rm
  --name latex yukinying/latex pdflatex --halt-on-error "/$file"; done

after_success:
- echo "SUCCESS!"
- git add tex/*.tex tex/*.pdf
- git commit -m 'generated TeX and PDF from Travis [skip ci]'
- git remote add deploy git@github.com:protograph/protograph.git
- GIT_SSH_COMMAND='ssh -i deploy.key' git push deploy HEAD:master
